const { productSchema } = require('../../schemas');

const products = [
  new productSchema({
    title: 'Floral Tropica',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F14%2F2021%2F05%2F21%2F052121-womens-2-piece-floral-and-tropical-print-crop-wrap-top-with-shorts-set-embed.jpg&q=85',
    categories: ['summer', 'spring', 'women', 'summer', 'shorts'],
    size: ['S', 'M', 'L'],
    color: ['white', 'blue', 'black'],
    price: '180',
  }),
  new productSchema({
    title: 'Loriana Dress',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://image.made-in-china.com/202f0j00lTJfVQNIAArm/Women-Summer-Clothing-White-Black-Spots-Dresses-Women-Lady-Casual.jpg',
    categories: ['summer', 'spring', 'women', 'casual'],
    size: ['S', 'M', 'L'],
    color: ['white', 'yellow', 'black'],
    price: '100',
  }),
  new productSchema({
    title: 'UK Flower',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://i.etsystatic.com/23047533/r/il/47c959/2901729236/il_1588xN.2901729236_fslm.jpg',
    categories: ['summer', 'spring', 'women', 'dress', 'casual'],
    size: ['S', 'M', 'XL'],
    color: ['white', 'yellow', 'white'],
    price: '90',
  }),
  new productSchema({
    title: 'Pinki winter',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://i.etsystatic.com/7367017/c/2000/1588/0/1050/il/3314ab/1733727438/il_680x540.1733727438_sga2.jpg',
    categories: ['winter', 'warm', 'women'],
    size: ['S', 'M', 'L', 'LX'],
    color: ['white', 'yellow', 'white', 'red'],
    price: '120',
  }),
  new productSchema({
    title: 'OBlue Sky',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://i.etsystatic.com/26021575/c/752/752/130/0/il/44aece/3009977190/il_300x300.3009977190_c6q0.jpg',
    categories: ['winter', 'warm', 'women'],
    size: ['S', 'M', 'L', 'LX'],
    color: ['white', 'blue', 'yellow', 'white', 'red'],
    price: '80',
  }),
  new productSchema({
    title: 'Cooly Summer',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.ltwebstatic.com/images3_pi/2020/12/28/1609140377ef02002dcd04c24f9c86bf0bea1c1238.webp',
    categories: ['summer', 'spring', 'women', 'shirt'],
    size: ['S', 'M', 'L', 'LX'],
    color: ['green', 'black', 'yellow', 'white', 'red'],
    price: '70',
  }),
  new productSchema({
    title: 'Victoria Wolf',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/20ecba80e91f06fc852359c35d9c2457_540x.jpeg',
    categories: ['winter', 'fall', 'women', 'shirt'],
    size: ['S', 'M', , 'LX'],
    color: ['green', 'blue', 'yellow', 'white', 'red'],
    price: '140',
  }),
  new productSchema({
    title: 'Raindrop Lee',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/d3afd3300339b7fbf82f33b3957e915e_540x.jpeg',
    categories: ['winter', 'fall', 'women', 'shirt'],
    size: ['S', 'M', , 'LX'],
    color: ['black', 'blue', 'yellow', 'white', 'red'],
    price: '130',
  }),
  new productSchema({
    title: 'Summery walker',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/04bdf90040dcb9a41ef8f940db0ff8cf_540x.jpeg',
    categories: ['summer', 'spring', 'women', 'shirt'],
    size: ['S', 'M', 'L', 'LX'],
    color: ['yellow', 'white', 'red'],
    price: '70',
  }),
  new productSchema({
    title: 'The Snow girl',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/09f441029bc61a0e8f58b5f1b3e4f3cb_540.jpeg',
    categories: ['winter', 'fall', 'women', 'shirt'],
    size: ['S', 'M', 'LX'],
    color: ['yellow', 'white', 'red', 'black'],
    price: '140',
  }),
  new productSchema({
    title: 'Reddish winter',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/2714da3a0c34a3dbd785553d1db28ad9_540x.jpeg',
    categories: ['winter', 'fall', 'women', 'shirt'],
    size: ['S', 'M', 'LX'],
    color: ['yellow', 'white', 'red', 'black'],
    price: '180',
  }),
  new productSchema({
    title: 'Snober Cat',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/315cc2b26490ba6f55c8d9c087efc8e0_540x.jpeg',
    categories: ['winter', 'fall', 'women', 'shirt'],
    size: ['S', 'M', 'LX'],
    color: ['yellow', 'white', 'red', 'black', 'blue', 'green'],
    price: '160',
  }),
  new productSchema({
    title: 'Sun & Flower',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/94319d76fb7e569257f0db4f53947e06_540x.jpeg',
    categories: ['spring', 'summer', 'women', 'shirt'],
    size: ['S', 'M', 'L'],
    color: ['yellow', 'white', 'red', 'black', 'blue', 'green'],
    price: '150',
  }),
  new productSchema({
    title: 'Sunny Blackfish',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/594aa3c676155fc5a6bc861cfd0a9420_540x.jpeg',
    categories: ['spring', 'summer', 'women', 'shirt'],
    size: ['S', 'M', 'L', 'XL'],
    color: ['yellow', 'white', 'red', 'black', 'blue', 'green'],
    price: '130',
  }),
  new productSchema({
    title: 'Gipouri ish',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/6aa1848b1b2438cb0c42fc603c9d58b3_540.jpeg',
    categories: ['spring', 'summer', 'women', 'shirt'],
    size: ['S', 'M', 'L', 'XL'],
    color: ['yellow', 'white', 'blue', 'green'],
    price: '80',
  }),
  new productSchema({
    title: 'Lorreti',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/ca5b9b56af33904028c28869b10716d0_540.jpeg',
    categories: ['spring', 'fall', 'women', 'shirt'],
    size: ['S', 'M', 'L', 'XL'],
    color: ['yellow', 'white', 'red', 'green'],
    price: '80',
  }),
  new productSchema({
    title: 'ColdWind',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/578b159727dd78a061a02707b90b3b25_540.jpeg',
    categories: ['spring', 'summer', 'women', 'jacket'],
    size: ['S', 'M', 'L', 'XL'],
    color: ['yellow', 'white', 'blue', 'green'],
    price: '90',
  }),
  new productSchema({
    title: 'Color Queen',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/5d86fcfc80591886c4b427aa622ca2a9_540.jpeg',
    categories: ['summer', 'spring', 'women', 'dress'],
    size: ['S', 'M', 'L', 'XL'],
    color: ['yellow', 'white', 'red', 'green'],
    price: '80',
  }),
  new productSchema({
    title: 'Redius Santa',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/d13dcf03312d397bc1c19979c8b50104_540.jpeg',
    categories: ['winter', 'fall', 'women', 'shirt'],
    size: ['S', 'M', 'XL'],
    color: ['yellow', 'white', 'red', 'green'],
    price: '70',
  }),
  new productSchema({
    title: 'Jeepy Tshirt',
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/c090f815338ef5d557cab5b27a936430_540.jpeg',
    categories: ['winter', 'fall', 'women', 'shirt', 'tshirt'],
    size: ['S', 'M', 'L'],
    color: ['yellow', 'white', 'red', 'green'],
    price: '75',
  }),
  new productSchema({
    title: "Violet's Reflect",
    desc: 'Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. ',
    img: 'https://img.staticdj.com/b6ae6c3e3be21099667c5c24fe1d2766_540.jpeg',
    categories: ['winter', 'fall', 'women', 'shirt'],
    size: ['S', 'M', 'L'],
    color: ['yellow', 'white', 'red', 'green'],
    price: '75',
  }),
];
module.exports = { products };
